import type { Metadata } from "next";
import "./globals.css";
import { FolderProvider } from "@/context/FolderContext";
import { ImageProvider } from "@/context/ImageContext";
import { SearchProvider } from "@/context/SearchContext";
import { NavigationLayout } from "@/components/NavigationLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="h-full antialiased font-sans"
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Host+Grotesk:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet" />
      </head>
      <body className="min-h-full flex flex-col bg-[#f0f2f5] dark:bg-zinc-950">
        <FolderProvider>
          <ImageProvider>
            <SearchProvider>
              <NavigationLayout>
                {children}
              </NavigationLayout>
            </SearchProvider>
          </ImageProvider>
        </FolderProvider>
      </body>
    </html>
  );
}
