import type { Metadata } from "next";
import "./globals.css";
import { BottomNav } from "@/components/BottomNav";
import { FolderProvider } from "@/context/FolderContext";
import { ImageProvider } from "@/context/ImageContext";
import { SearchProvider } from "@/context/SearchContext";
import { SearchBar } from "@/components/SearchBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="h-full antialiased font-sans"
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Host+Grotesk:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet" />
      </head>
      <body className="min-h-full flex flex-col bg-[#f0f2f5] dark:bg-zinc-950">
        <FolderProvider>
          <ImageProvider>
            <SearchProvider>
              {/* Header */}
              <div className="sticky top-0 z-[100] w-full px-5 py-4 flex items-center justify-between gap-4 bg-[#f0f2f5]/80 dark:bg-zinc-950/80 backdrop-blur-md border-b border-black/5 dark:border-white/5">
                <img src="/logo.png" alt="Logo" className="h-10 w-auto object-contain" />
                <SearchBar />
              </div>

              <div className="flex-1 flex flex-col">
                {children}
              </div>
              <div className="w-full flex items-center justify-center gap-3 pb-32 pt-4 opacity-80">
                <span className="text-2xl font-bold dark:text-white">With</span>
                <span className="heart text-[40px]">❤️</span>
                <img src="/logo.png" alt="Logo" className="h-8 w-auto object-contain" />
              </div>
              <BottomNav />
            </SearchProvider>
          </ImageProvider>
        </FolderProvider>
      </body>
    </html>
  );
}
